version: "3.8"
services:
    djang_weather:
      command: python DjangoWhetherProject/manage.py runserver 0.0.0.0:8000
      build:
          context: .
          dockerfile: Dockerfile
      ports:
        - 8000:8000
      volumes:
        - .:/app