# Generated by Django 4.0.5 on 2022-06-06 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, unique=True, verbose_name="slug for city name"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "db_table": "cities",
            },
        ),
        migrations.CreateModel(
            name="DayCityWheather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wind_kph",
                    models.FloatField(
                        verbose_name="maximum wind speed in kilometer per hour"
                    ),
                ),
                (
                    "wind_dir",
                    models.CharField(
                        max_length=10, verbose_name="Wind direction as 16 point compass"
                    ),
                ),
                (
                    "wind_degree",
                    models.FloatField(verbose_name="wind direction in degrees"),
                ),
                (
                    "precip_mm",
                    models.FloatField(
                        verbose_name="precipitation amount in millimeters"
                    ),
                ),
                (
                    "feelslike_c",
                    models.FloatField(verbose_name="feels like temperature as celcius"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("condition_text", models.TextField(verbose_name="condition text")),
                (
                    "icon_number",
                    models.PositiveIntegerField(verbose_name="number of icon"),
                ),
                ("date", models.DateField(verbose_name="wheather date")),
                ("maxtemp_c", models.FloatField(verbose_name="max temp celsius")),
                ("maxtemp_f", models.FloatField(verbose_name="max temp fahrenheit")),
                ("mintemp_c", models.FloatField(verbose_name="min temp celsius")),
                ("mintemp_f", models.FloatField(verbose_name="min temp fahrenheit")),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wheather.city"
                    ),
                ),
            ],
            options={
                "db_table": "days",
            },
        ),
        migrations.CreateModel(
            name="HoursDayWheather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wind_kph",
                    models.FloatField(
                        verbose_name="maximum wind speed in kilometer per hour"
                    ),
                ),
                (
                    "wind_dir",
                    models.CharField(
                        max_length=10, verbose_name="Wind direction as 16 point compass"
                    ),
                ),
                (
                    "wind_degree",
                    models.FloatField(verbose_name="wind direction in degrees"),
                ),
                (
                    "precip_mm",
                    models.FloatField(
                        verbose_name="precipitation amount in millimeters"
                    ),
                ),
                (
                    "feelslike_c",
                    models.FloatField(verbose_name="feels like temperature as celcius"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("condition_text", models.TextField(verbose_name="condition text")),
                (
                    "icon_number",
                    models.PositiveIntegerField(verbose_name="number of icon"),
                ),
                ("time", models.DateTimeField(verbose_name="wheather time")),
                ("temp_c", models.FloatField(verbose_name="temp celsius")),
                ("temp_f", models.FloatField(verbose_name="temp fahrenheit")),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wheather.daycitywheather",
                    ),
                ),
            ],
            options={
                "db_table": "hours",
            },
        ),
    ]
