# Generated by Django 4.0.5 on 2022-06-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wheather", "0002_rename_wind_degrees_daycitywheather_wind_degree_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=200,
                unique=True,
                verbose_name="slug for city name",
            ),
        ),
    ]
