# Generated by Django 4.0.5 on 2022-06-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wheather", "0002_rename_wind_degrees_daycitywheather_wind_degree_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="slug",
            field=models.SlugField(
                default="", unique=True, verbose_name="slug for attribute"
            ),
            preserve_default=False,
        ),
    ]
